### ISSUE TITLE
triple queries ignore database index

### ISSUE THREAD

**Issue by mro** [mro/librdf.sqlite#11]
librdf.sqlite uses one single, precompiled, large `SELECT` [query](https://github.com/mro/librdf.sqlite/blob/6b53ca31dec62f67ad2aacff013bea8d435e35d5/find_triples.sql#L47) with a bit of boolean algebra to retrieve triples. But sadly sqlite doesn't like that when it comes to indexes:

    CREATE TABLE demo (
      id INTEGER PRIMARY KEY
    );
    EXPLAIN QUERY PLAN SELECT * FROM demo WHERE 0 OR id=3;
    EXPLAIN QUERY PLAN SELECT * FROM demo WHERE id=3;

where the first query ignores the index, the 2nd uses it (according to the estimated query plan).

    $ sqlite3 --version
    3.7.12 2012-04-03 19:43:07 86b8481be7e76cccc92d14ce762d21bfb69504af

**Comment by mro** [comment]
asked on the sqlite-users list: http://mailinglists.sqlite.org/cgi-bin/mailman/private/sqlite-users/2015-October/062586.html

**Comment by mro** [comment]
confirmed:

> The query planner in SQLite does not (currently) recognize the special case of "0 OR ...".  Hence, the only way to get it to use an index is the second form of the query.
> --
> D. Richard Hipp

**Comment by mro** [comment]
so I think I will

- prepare an (empty) array of precompiled statements (2^9 or 1<<8 or 512)
- use bitmasks to create an index of the query dependent on which parameters are non-null
- dynamically create queries on demand once and cache them.

evtl. use a `set_feature` to control how aggressive/memory consuming the caching may be, because 512 statements is more than feels comfortable.

**Comment by rtravis** [comment]
You won't be using 512 prepared statements, even though, you still need 9 bits if you want to create a bit-mask index or key.

If I am not mistaken, for searching RDF statements, there are 3 x 2 x (1 + 1 + 1 + 3) x 2 = 72 possible queries:

Subject:
3 possibilities: is resource, is blank, is null

Predicate:
2 possibilities: yes or no

Object:
1 possibility: is resource
1 possibility: is blank
1 possibility: is null
3 possibilities for is literal(lang, type): (null, null), (lang, null|rdf:langString), (null, type)

Context:
2 possibilities: yes or no

If you want to build a contiguous index from 0 to 71 to select the prepared statement, you can use a technique similar to the one used in the "find_statement" function in the [rdf_storage_firebird.cpp](https://github.com/rtravis/librdf.firebird/blob/master/src/rdf_storage_firebird.cpp) file.

**Comment by mro** [comment]
@rtravis yes, good point. So if I keep the 2^9-statement-pointer-array (for simplicity sake) it will be sparsely populated. I had a look at your [find_statement](https://github.com/rtravis/librdf.firebird/blob/7e8b87636383ba200bd5fcf1e496327a7cde8995/src/rdf_storage_firebird.cpp#L474) and hope to go with less then 300 LOC and rather waste some memory (for now).

**Comment by mro** [comment]
@abargnesi I'm curious if the code in branch `feature/issue11` serves the purpose.
Writing a `loader.c` that puts retrieval speed as well as feature completeness & correctness under test would be a great help.
Especially literal value, datatype and language filter semantics need testing (not due this code change but in general).

**Comment by abargnesi** [comment]
@mro 
:+1:

I will take a look at writing an example main to exercise changes in the `feature/issue11`. This could also be split up into check tests and incorporated with the compilation.

With these changes I noticed what I think is an mistype, patch below:

```diff
diff --git a/rdf_storage_sqlite_mro.c b/rdf_storage_sqlite_mro.c
index 10e7269..b1073ec 100644
--- a/rdf_storage_sqlite_mro.c
+++ b/rdf_storage_sqlite_mro.c
@@ -1328,7 +1328,7 @@ static librdf_stream *pub_context_find_statements(librdf_storage *storage, librd
         | (LIBRDF_NODE_TYPE_RESOURCE == node_type(s) ? P_S_URI : 0)
         | (LIBRDF_NODE_TYPE_BLANK == node_type(s) ? P_S_BLANK : 0)
         | (LIBRDF_NODE_TYPE_RESOURCE == node_type(p) ? P_P_URI : 0)
-        | (LIBRDF_NODE_TYPE_RESOURCE == node_type(o) ? P_P_URI : 0)
+        | (LIBRDF_NODE_TYPE_RESOURCE == node_type(o) ? P_O_URI : 0)
         | (LIBRDF_NODE_TYPE_BLANK == node_type(o) ? P_O_BLANK : 0)
         | (LIBRDF_NODE_TYPE_LITERAL == node_type(o) ? P_O_TEXT : 0)
         | (librdf_node_get_literal_value_datatype_uri(o) ? P_O_DATATYPE : 0)

```

**Comment by rtravis** [comment]
Nice job.

Testing a SPARQL query with the code from 'issue11' I got a segmentation fault. The issue seems to be that: librdf_node_get_literal_value_datatype_uri and librdf_node_get_literal_value_language are called with a null argument in the pub_context_find_statements function:

        | (librdf_node_get_literal_value_datatype_uri(o) ? P_O_DATATYPE : 0)
        | (librdf_node_get_literal_value_language(o) ? P_O_LANGUAGE : 0)

So I think null needs to be checked there.

**Comment by rtravis** [comment]
Unfortunately there are more problems:

sizeof(find_triples_sql) is 8 assuming 64 bit pointers. So the statements:

    char sql[sizeof(find_triples_sql) + 1];
    strcpy(sql, find_triples_sql);

overwrite and corrupt the stack memory. sqlite3_reset mustn't be called if the statement hasn't been executed. It's purpose should be only for the case when we re-execute a prepared statement.

I could not attach the patch file to this post so I pushed it to my fork of [librdf.sqlite](https://github.com/rtravis/librdf.sqlite/commit/a56c2e69a8258e1fc438309faf7403f14d1f3526)

**Comment by mro** [comment]
thanks, am about fixing..

**Comment by mro** [comment]
@rtravis can't follow - both `sql` `find_triples_sql` and are `char` arrays.

**Comment by rtravis** [comment]
@mro think of this example:

    const char *s1 = "1234567890abcdef"; // sizeof(s1) == 8 (sizeof a pointer to char)
    const char s2[] = "1234567890abcdef"; // sizeof(s2) == 17 (size of array including null terminator)

**Comment by mro** [comment]
@rtravis thank you for pointing me to this. That would never have come to my mind.

**Comment by rtravis** [comment]
I was wrong about sqlite3_reset crashing with un-executed sqlite statements. It is not so.

However, after pulling the latest code, I still encounter a segmentation fault with my setup in cleanup code. I could not find the reason until now. Removing the call to sqlite3_reset in finalize_stmt seems to make the segfault go away, but that is not a fix.

I created a [gist](https://gist.github.com/rtravis/199f853106ed7e9c5840#file-librdf-sqlite_issue11_3-txt) showing gdb debugger output. I will still this investigate for a while. If you need more information I can provide it.

**Comment by mro** [comment]
indeed. I was also puzzled by your report on `sqlite3_reset` didn't see it myself yet, so I ttok no action for now. Can you provide the test program?

Maybe `sqlite3_reset` tries to free memory that isn't allocated no more. Maybe even stack memory. Many maybes.

**Comment by rtravis** [comment]
[Here](https://gist.github.com/rtravis/d5a6b1b15972a8ce6d87) that I use to replicate the issue. It's C++ :(.  With it you can run just about any SPARQL query against your model.

I am curious if it behaves the same way in your environment also.

**Comment by mro** [comment]
same here https://gist.github.com/mro/1d173e9195d088288e81 (debian wheezy amd64)

**Comment by mro** [comment]
even getting the sql via `sqlite3_sql(db_ctx->stmt_triple_finds[i])` does odd things. Using `malloc`ed memory for the sql - even leaking it - seems worth investigating (the sql prints now) but didn't solve the segfault either.

Running through valgrind overwhelmed me with information I cannot make sense of for now.

**Comment by rtravis** [comment]
I think I found something related to the segfault. Please check this [pull request](https://github.com/mro/librdf.sqlite/pull/12/files) and see if it is OK.

**Comment by mro** [comment]
@abargnesi can you confirm issue resolved thanks to @rtravis and #12 ?

**Comment by rtravis** [comment]
A compiler warning made me attentive. Parentheses are needed in this expression:

    if( params == db_ctx->sql_cache_mask & params )

`operator ==` has higher precedence than `operator &` so the above expression is evaluated as either `0 & params` or as `1 & params`.

First `params == db_ctx->sql_cache_mask` is evaluated the result is a boolean value (in C++ it's always 0 and 1, probably in C also). The boolean value is then promoted to integer (0 or 1) if necessary to match the second argument in the `& operator`. Then the `& operator` is evaluated with the promoted integer and the `params` variable.

**Comment by mro** [comment]
merged to master
