### ISSUE TITLE
SPARQL query gives incorrect results

### ISSUE THREAD

**Issue by rtravis** [mro/librdf.sqlite#17]
Steps to reproduce:

Import the following RDF data into an empty librdf.sqlite store:

``` Turtle
@prefix dbpont: <http://dbpedia.org/ontology/>.
@prefix dbpres: <http://dbpedia.org/resource/>.
@prefix foaf: <http://xmlns.com/foaf/0.1/>.

dbpres:The_Art_of_Computer_Programming 
    a dbpont:Book ;
    dbpont:author dbpres:Donald_Knuth ;
    foaf:name "The Art of Computer Programming" ;
    dbpont:isbn "0-201-03801-3" ;
    dbpont:numberOfPages "634"^^<http://www.w3.org/2001/XMLSchema#integer> ;
    dbpont:mediaType dbpres:Hardcover .

dbpres:The_Republic_\(Plato\)
    a dbpont:Book ;
    dbpont:author dbpres:Plato ;
    foaf:name "Republic"@en ;
    dbpont:language dbpres:Greek_language .
```

Run the following SPRAQL query against the imported model:

``` SPARQL
SELECT ?author ?title
WHERE {
       ?book a <http://dbpedia.org/ontology/Book> .
       ?book <http://xmlns.com/foaf/0.1/name> ?title .
       ?book <http://dbpedia.org/ontology/author> ?author .
}
```

Expected result:

| author | title |
| --- | --- |
| http://dbpedia.org/resource/Plato | Republic |
| http://dbpedia.org/resource/Donald_Knuth | The Art of Computer Programming |

Actual result:

| author | title |
| --- | --- |
| The Art of Computer Programming | The Art of Computer Programming |
| Republic | Republic |

Software used:

librdf.sqlite 0.1
redland 1.0.17-1
raptor2 2.0.14-1
rasqal 0.9.32-1

**Comment by mro** [comment]
how would I run a SPARQL query from C, preferably a test similar to `test-example1.c`?

I tried for more than an hour without success.

**Comment by mro** [comment]
ok, one step further, an assert fires ([travis build](https://travis-ci.org/mro/librdf.sqlite/builds/95880700)):
```
...
librdf info - Created SQL statement #12
librdf info - Created SQL statement #5
test-issue17: ../rdf_storage_sqlite_mro.c:1625: librdf_stream *pub_context_find_statements(librdf_storage *, librdf_statement *, librdf_node *): Assertion `0 == rc && "find_statements: failed to bind SQL parameters"' failed.
make: *** [build/test-issue17] Aborted (core dumped)
...
```

**Comment by mro** [comment]
mind that I replaced one prefix url form with `<http://dbpedia.org/resource/The_Republic_(Plato)>` because [rapper](http://librdf.org/raptor/rapper.html) didn't like it either.

**Comment by mro** [comment]
the parameter binding needs a rework. Bitmask has to be key which params to bind. IMO binding a nonex name causes the current failure.

**Comment by rtravis** [comment]
I think that the issue is caused by re-using an SQLite prepared statement by a different query while the first query has not finished fetching all the results.

During the SPARQL query the prepared statement 'ps1' is created for query 'q1' and parameter 'p1' is set. With a result row fetched by 'ps1', Rasqal requests the prepared statement 'ps2' resets it and sets parameter 'p1' to another value. When the results of 'ps2' are exhausted, Rasqal proceeds to the next row of 'ps1' and so on.

The bug is caused because 'ps1' and 'ps2' are in fact the same - cached - prepared statement.

**Comment by rtravis** [comment]
I encountered this problem while developing [librdf.firebird](https://github.com/rtravis/librdf.firebird) and solved it by keeping a list of cached prepared statements for each possible SQL query.

While a SQL query is in progress, the cached prepared statement is marked as in use. If in the same time another request is made for the same SQL query we either chose a free prepared statement or we create a new one. Search for `acquireMatchStatement` and `releaseMatchStatement` for more details.

**Comment by mro** [comment]
@rtravis seems fixed, finally. Thanks for reporting, do you want to confirm?

**Comment by rtravis** [comment]
The issue seems to be fixed indeed. I tested it with the code from latest master branch commit: a5515c844.
