### ISSUE TITLE
instructions on how to integrate with librdf's build process

### ISSUE THREAD

**Issue by bedax** [mro/librdf.sqlite#18]
Hi, sorry if this is obvious, my knowledge of C and librdf's build process are very limited, but would it be possible to provide information (in the readme or wherever) on how to integrate this with librdf's build process? Ideally I would like to be able to drop this into librdf's source and have its build script compile this as a normal storage module, is that possible?

Thanks a lot for this project, by the way

**Comment by mro** [comment]
hi @bedax, just copy `rdf_storage_sqlite_mro.c`and `.h` to your project, compile and link against librdf with whatever build process you have. Usually `pkg-config` to find header and library of librdf. On iOS the CocoaPod may be helpful (or may not).

The `test/*.c` test programs for example use a plain old makefile.

Hope this helps.

**Comment by bedax** [comment]
Brilliant, thanks for that @mro! That really helps a lot
