### ISSUE TITLE
Feature request: contexts

### ISSUE THREAD

**Issue by bedax** [mro/librdf.sqlite#19]
Hi, are there any plans to support contexts? I don't know how much work this would involve but it would be very nice to have

**Comment by mro** [comment]
aren't they? What's missing? The triples would have to be expanded to quadrupels, right?

**Comment by bedax** [comment]
ah I see that they are supported. My writes were failing when I was using this store with `librdf_model_context_add_statement`, librdf said `librdf warning - Model does not support contexts`, so that led me to assume that they weren't supported. I changed that call to `librdf_storage_context_add_statement` and I see now that they're getting added. 

Now `librdf_model_query_execute` is coming up empty, even after successfully adding a statement with the above and running a simple query like: 

```
SELECT ?s ?p ?o ?c WHERE {
    GRAPH ?c { ?s ?p ?o }
}
```

`librdf_storage_query_execute` doesn't work either. I'm not sure why. If it's obvious to you I'd be grateful to hear it, but otherwise I'll keep searching.

**Comment by rtravis** [comment]
@bedax I think that the issue you mentioned in the post above is not in the librdf.sqlite storage module, but in the Rasqal query library used by Librdf. As mentioned here: http://librdf.org/query/, Rasqal does not implement all of SPARQL, notably the GRAPH construct is not supported.

**Comment by bedax** [comment]
Thanks for the response @rtravis. I'm not sure, but as far as I can tell, it seems that librdf doesn't support GRAPH in a conventional sense, instead it uses the GRAPH keyword for contexts.

It's hard to find information on this, all I cam really find is in the releases page: http://librdf.org/RELEASE.html

> Graph names in SPARQL now connect up to redland context nodes to allow SPARQL GRAPH to work.

> Fix rasqal query engine integration to allow querying over the Redland graph names (context URIs) and binding variables to the names. Fixes Issue [#000382](http://bugs.librdf.org/mantis/view.php?id=382).  

The linked issue gives basically the same query example and error description that I mentioned above.

> [fixed] Issue #0000366: SELECTing list of named graphs doesn't return any results

Which again gives the same example query, which now works with librdf's default stores, which I have tested and have been using.

I hope this issue has the same fix as those I linked to, otherwise I'm not sure.

**Comment by mro** [comment]
uh, interesting. @bedax / @rtravis , do you think there's something `librdf.sqlite` could/should do or is this issue to be closed?

**Comment by bedax** [comment]
@mro librdf.sqlite isn't consistent with the default stores in how it deals with the above query. The default stores bind the statement's context to `?c`, whereas librdf.sqlite seems to not, resulting in empty results when the query is executed. The two linked issues above link to the patch that fixed this for the default stores.

Also `librdf_model_context_add_statement` fails with `librdf warning - Model does not support contexts`, which would be nice if it didn't, although this one doesn't seem as important as `librdf_storage_context_add_statement` can be used instead.

Perhaps I should open two new issues for these, as I started this thread not knowing what was wrong. I'm still not sure what could be done, as I'm not hugely familiar with librdf's internals.

**Comment by mro** [comment]
@bedax happy with #20?

**Comment by bedax** [comment]
@mro it works perfectly, it passes all my tests so i'll close this now. thank you both very much for your help!
